### ISSUE TITLE
Song too long decision based on duration instead of size

### ISSUE THREAD

**Issue by 8sd** [raveberry/raveberry#10]
`youtube-dl` does not always provide filesize. 
`Spotify` doesn't do it either → use duration of songs

**Comment by 8sd** [comment]
Is this necessary for Spotify, there are only a few long songs?

**Comment by raveberry** [comment]
mopidy-spotify streams with a default bitrate of 160kbps. This is now (0.8.2) used to estimate whether a song fits into the specified download limit.
