### ISSUE TITLE
Question: is there a way to browse available music

### ISSUE THREAD

**Issue by tmuras** [raveberry/raveberry#100]
Is there a way to browse (as opposed to search) through available (ie local) music or playlists.

**Comment by raveberry** [comment]
No, currently there is no way to do that in a comfortable way. The least inconvenient way is probably to visit django's admin page at `http://raveberry/admin/` and navigate to `/core/archivedsong/`. Each entry in this table corresponds to a played song.
Similarly `/core/archivedplaylist/` contains all playlists.
