### ISSUE TITLE
Blacklist.... doesnt work.

### ISSUE THREAD

**Issue by mxpowe** [raveberry/raveberry#102]
No matter what name, word or anything I put in the block songs from spotify list, it never works to block the songs.

Am I missing something?

I should say the upgrade ran perfectly to 8.1 from 7.x, no issues, just clicked and after a while it was great.

**Comment by raveberry** [comment]
Happy to hear that the upgrade worked! I was worried that something might go wrong in the process.

Just had to test the blocking feature myself, as I don't usually use it. Some things that might not be obvious:
- Keywords are specified comma separated
- Only the title of a song is filtered, not the artist
- Suggestions are not affected, only new searches (->magnifying glass) are

Other than that filtering worked for me. Can you give me an example where it doesn't? Do you need suggestions or artists to be filtered?

**Comment by mxpowe** [comment]
Ahh it was artists I was listing.

**Comment by raveberry** [comment]
Sure, I think filtering the artist (and suggestions as well while we're at it) would be the more intuitive behavior. I will include it in the next release.

**Comment by raveberry** [comment]
With 0.8.2, the filter keywords are applied to suggestions and the artist as well.
Additionally, youtube and local songs are also subject to filtering.
This should solve your use case and provides a more consistent behavior.
