### ISSUE TITLE
Explain installation process better

### ISSUE THREAD

**Issue by mxpowe** [raveberry/raveberry#105]
During a new install using the "pip3 install raveberry[install]
raveberry system-install"

Users are not prompted for any options like spotify, youtube and or soundcloud. 
A base install installs youtube and in the settings it states that spotify must be specified during the install.

**Comment by FluidExtractor** [comment]
I'm pretty sure the installer tells you to make changes to the config before installing if you want soundcloud or spotify.
But yeah, also having that option in the installer would be nice.

**Comment by raveberry** [comment]
Correct, as @FluidExtractor said, `system-install` will ask for confirmation on the config file that is used for installation:
```
$ raveberry system-install
You are about to install raveberry system-wide. This will make it start on boot and enable features specified in the config file.
    Depending on your configuration, this will alter some system files. (Although everything *should* work fine, backups are recommended)
    Config-file location: /home/pi/.local/lib/python3.7/site-packages/raveberry/config/raveberry.yaml
Is this the configuration you want to install raveberry with? [Y/n] 
```
This is the moment where you would be able to open the given config file and make changes to it, such as enabling Spotify. The reasoning for this behavior is that I wanted to make a base installation as straight forward as possible, which would not be the case if the installation prompted for every possible decision.
If you want to extend the functionality of your current installation, you can simply reinstall with a changed config file.

Would you rather have an interactive installation? Do you have other ideas to make it more intuitive?

**Comment by FluidExtractor** [comment]
@raveberry You don't have to make the installer prompt users for every single decision. You could add just the music service choice to the installer, as I think that the default config is good enough for users that just want Raveberry to work. 

Either that, or you could add a line to the `system-install` confirmation dialog that tells users  they have to modify the config file if they want Spotify or Soundcloud.
That would help avoid situations like: "I want Spotify to work but Raveberry tells me that I had to specify that during installation. But the installer did not ask me for that."

**Comment by mxpowe** [comment]
I think the install directions on the readme can be a bit confusing when walked through....

- raveberry system-install
- Is this the configuration you want to install raveberry with? [Y/n] n
- Then the install halts.
I selected n because I thought I was going to be given a choice to change it.

Perhaps when the option is selected in the raveberry/settings page post installation, it will install spotify then. That way the base install can remain lean?

Also... the readme is a bit confusing...
Installation
Try it out...
sudo apt-get install -y python3-pip mopidy ffmpeg gstreamer1.0-plugins-bad
pip3 install raveberry[run]
raveberry run
**This method uses a development server, with limited performance and a restricted feature set.**

So, one would think the next section is what is used to perform a full install...
Installation
In order to gain access to all features of Raveberry, perform a system installation:
pip3 install raveberry[install]
raveberry system-install 
But if they skip the first "try it out" then the second method wont work unless the user reboots after the pip3 install raveberry and then runs the raveberry system-install. WIthout the reboot, they are told raveberry isnt found.

**Comment by mxpowe** [comment]
I just want to say that I love your software, we use it in our bar and its a HIT. Although the bar has been closed 9 of the last 14 months :(

I do appreciate the work you do!

**Comment by raveberry** [comment]
Alright, thanks for your input. I see that the message should be made clearer. My take would be something like this:
```
$ raveberry system-install
This install will change system files, backups are recommended.
	config: /home/pi/.local/lib/python3.7/site-packages/raveberry/config/raveberry.yaml
For advanced features (e.g. Spotify, Visualization, Hotspot) edit the config before continuing.
Continue? [Y/n]
```

As for the readme structure: the system install is possible without performing the "Try it out" steps first. It's just that the `raveberry` executable is probably located in `~/.local/bin` and not available in `$PATH`. There is a note about this in the "Try it out" section, but not in the install section. I will add it there as well.

Do you have suggestions how I could make these first sections less confusing?

Also, I'm thrilled to hear that you make use of this software in a bar! I can't wait until we can return to our normal life again.

**Comment by mxpowe** [comment]
I will give a shot at editing the installation instructions this week.

**Comment by raveberry** [comment]
I did some minor rewording, but I'm always open for suggestions.

**Comment by mxpowe** [comment]
Just got the notice of the update, Great Job! Gonna do another start to finish install today.
