### ISSUE TITLE
Save played songs as playlist

### ISSUE THREAD

**Issue by mxpowe** [raveberry/raveberry#106]
It would be great to be able to save a playlist and load that playlist from the local file storage.

Example, 
20 people in the bar, they all pick great music, I delete all the crap throughout the night etc and at the end of the night, it would be nice to save that playlist thats on the Raveberry (repeat) to a local file and reload it.

**Comment by raveberry** [comment]
That's a great idea and it would be a very handy feature to have.

The clean way to implement this would be to add a new page `/playlists` or something. There would be an overview over every playlist, and each could be deleted or modified (reorder, add, delete songs). Similarly, new playlists could be added.
However, this would take a lot of time (UI, interaction, logic) which I'll probably rather invest into other features.

There is an alternative, though. While not quite as convenient, it's a lot less effort to implement. There is already the "Analyze" feature in `/settings`, where the played songs for a given time frame can be shown. I could add a new button "Create Playlist":

![20210414-180800](https://user-images.githubusercontent.com/53476237/114742843-6a370c80-9d4c-11eb-8445-223fdb123d33.png)

This would create a new playlist with the provided name, containing all songs in the given timespan.
Afterwards, you could go to `/admin/core/playlistentry/` and delete those entries from that playlist that you want to have removed.
Afterwards you could enqueue this playlist like other playlists by searching for it by name.

Would that also work for you?

**Comment by mxpowe** [comment]
Sounds like a solid plan!

**Comment by raveberry** [comment]
This is now part of Raveberry with 0.8.5. If you have problems, let me know and we should be able to work it out.
