### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by mxpowe** [raveberry/raveberry#108]
Can someone explain exactly what these two icons do?

![Capture](https://user-images.githubusercontent.com/63602731/115824428-e62cf680-a3d5-11eb-8c5c-291bd858d5ff.PNG)

**Comment by raveberry** [comment]
Sure (I assume you mean the Youtube and Spotify icon):
Below the controls for the visualization an icon for each enabled platform will appear. Possible options currently are: local, youtube, spotify and soundcloud. Platforms can be enabled in `/settings`.
Users can use these icons to choose their preferred platform. When they search for something, it will first be processed by the selected platform. If no result was found on the preferred platform, or no preferred platform was chosen, Raveberry will fall back to the other platforms until a result is found or all enabled platforms are exhausted.
The order currently is local, Soundcloud, Spotify, Youtube.
Links to songs always get processed by the correct platform however.

Most of the time, users will not have to use this at all. Sometimes, it's useful however. For example, someone knows that a song is only on Youtube and a query that leads to this song would find another song in Spotify. By tapping the Youtube icon, they can explicitly search Youtube first.

Hope this helps.

**Comment by mxpowe** [comment]
Ahh that explains it! Thank you sir
