### ISSUE TITLE
Preload light.css

### ISSUE THREAD

**Issue by 8sd** [raveberry/raveberry#11]
When switching to the light theme the `.css`-file has to be loaded and the site is broken for a short time.
After the page was successfully loaded, the file could be pre-cached.

**Comment by stappjno** [comment]
The .css file is not the problem because it is really small. A precache does not solve the problem because many pngs are loaded if you change the theme and that generates much extra http requests. I suggest replacing pngs with svgs and change the color via css fill property.

**Comment by raveberry** [comment]
Thanks for the hint!
0.8.3 replaces all pngs with svgs and their color is controlled with css. Changing from scss to css variables also removes the need for two separate stylesheets, theming is now done by setting a `light` class for the `html` element. No loading of additional resources is necessary.
