### ISSUE TITLE
Server Error (500) 

### ISSUE THREAD

**Issue by movioli** [raveberry/raveberry#111]
Hello Guys i have an issue when i try to login to any user, i get the server error (500)
this is the log from /opt/raveberry/logs/error.log. I started with an fresh image of raspian. And then followed the instructions for raveberry.

```
2021-06-30 10:06:22 log.log_response:228 ERROR  Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/auth/views.py", line 61, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/generic/edit.py", line 141, in post
    if form.is_valid():
  File "/usr/local/lib/python3.7/dist-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.7/dist-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/local/lib/python3.7/dist-packages/django/forms/forms.py", line 382, in full_clean
    self._clean_form()
  File "/usr/local/lib/python3.7/dist-packages/django/forms/forms.py", line 409, in _clean_form
    cleaned_data = self.clean()
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/auth/forms.py", line 205, in clean
    self.user_cache = authenticate(self.request, username=username, password=password)
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/auth/backends.py", line 20, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/auth/base_user.py", line 44, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
 File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    return list(result)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/compiler.py", line 1554, in cursor_iter
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/compiler.py", line 1554, in <lambda>
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 96, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/postgresql/utils.py", line 6, in utc_tzinfo_factory
    raise AssertionError("database connection isn't set to UTC")
AssertionError: database connection isn't set to UTC
```

> new error log

**Comment by raveberry** [comment]
Hi,
Is this the full content of the error.log? It seems to miss the line containing the actual error.
Did the installation complete without errors? `raveberry system-install` should abort with an error message in case a task fails.

**Comment by movioli** [comment]
this is all i got in the error.log and the installation also showed no errors

> This install will change system files, backups are recommended.
> For advanced features (e.g. Spotify, Visualization, Hotspot) edit the config before continuing.
>     config: /home/pi/.local/lib/python3.7/site-packages/raveberry/config/raveberry.yaml
> Continue? [Y/n] y
> [DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the 
> controller starting with Ansible 2.12. Current version: 3.7.3 (default, Jan 22 
> 2021, 20:04:44) [GCC 8.3.0]. This feature will be removed from ansible-core in 
> version 2.12. Deprecation warnings can be disabled by setting 
> deprecation_warnings=False in ansible.cfg.
> 
> PLAY [System Install of Raveberry] *********************************************
> 
> TASK [Gathering Facts] *********************************************************
> ok: [localhost]
> 
> TASK [Read Raspberry Pi model] *************************************************
> ok: [localhost]
> 
> TASK [Set Raspberry Pi facts] **************************************************
> ok: [localhost]
> 
> TASK [Load config] *************************************************************
> ok: [localhost]
> 
> TASK [Set correct ssh key path] ************************************************
> skipping: [localhost]
> 
> TASK [Create target install directory] *****************************************
> ok: [localhost]
> 
> TASK [Copy Raveberry files to the remote] **************************************
> ok: [localhost]
> 
> TASK [Copy Raveberry config to the remote] *************************************
> ok: [localhost]
> 
> TASK [Install gpg] *************************************************************
> ok: [localhost]
> 
> TASK [Add mopidy gpg key] ******************************************************
> ok: [localhost]
> 
> TASK [Add mopidy repository] ***************************************************
> ok: [localhost]
> 
> TASK [Install apt dependencies (may take some time)] ***************************
> ok: [localhost]
> 
> TASK [pip self-update] *********************************************************
> ok: [localhost]
> 
> TASK [Install python dependencies (may take some time)] ************************
> ok: [localhost]
> 
> TASK [Install Youtube dependencies: Install apt dependencies] ******************
> ok: [localhost]
> 
> TASK [Install Youtube dependencies: Install python dependencies] ***************
> ok: [localhost]
> 
> TASK [Install Spotify dependencies: Install apt dependencies] ******************
> ok: [localhost]
> 
> TASK [Install Spotify dependencies: Install python dependencies] ***************
> ok: [localhost]
> 
> TASK [Install Soundcloud dependencies: Install apt dependencies] ***************
> skipping: [localhost]
> 
> TASK [Install Soundcloud dependencies: Install python dependencies] ************
> skipping: [localhost]
> 
> TASK [Install hotspot dependencies] ********************************************
> skipping: [localhost]
> 
> TASK [Install screen visualization dependencies: Install apt dependencies] *****
> skipping: [localhost]
> 
> TASK [Install screen visualization dependencies: Install python dependencies] ***
> skipping: [localhost]
> 
> TASK [Install buzzer dependencies] *********************************************
> skipping: [localhost]
> 
> TASK [Install led visualization dependencies] **********************************
> skipping: [localhost]
> 
> TASK [Check if cava executable is present] *************************************
> ok: [localhost]
> 
> TASK [Install cava: Install apt dependencies] **********************************
> skipping: [localhost]
> 
> TASK [Install cava: Git checkout] **********************************************
> skipping: [localhost]
> 
> TASK [Install cava: Build] *****************************************************
> skipping: [localhost] => (item=./autogen.sh) 
> skipping: [localhost] => (item=./configure) 
> skipping: [localhost] => (item=make) 
> skipping: [localhost] => (item=make install) 
> 
> TASK [Check if rganalysis executable is present] *******************************
> ok: [localhost]
> 
> TASK [Install rganalysis: Install apt dependencies] ****************************
> skipping: [localhost]
> 
> TASK [Install rganalysis: Uninstall new faad] **********************************
> skipping: [localhost]
> 
> TASK [Install rganalysis: Download faad2] **************************************
> skipping: [localhost]
> 
> TASK [Install rganalysis: Download faad2] **************************************
> skipping: [localhost]
> 
> TASK [Install rganalysis: Install faad2] ***************************************
> skipping: [localhost]
> 
> TASK [Install rganalysis: Install rganalysis] **********************************
> skipping: [localhost]
> 
> TASK [Install system scripts] **************************************************
> changed: [localhost]
> 
> TASK [Create backup folder] ****************************************************
> changed: [localhost]
> 
> TASK [Backup files: Ensure directories exist] **********************************
> changed: [localhost] => (item=boot)
> changed: [localhost] => (item=etc)
> changed: [localhost] => (item=etc/default)
> changed: [localhost] => (item=etc/pulse)
> 
> TASK [Backup files: Copy files] ************************************************
> changed: [localhost] => (item=/boot/config.txt)
> ok: [localhost] => (item=/etc/default/hostapd)
> changed: [localhost] => (item=/etc/dhcpcd.conf)
> ok: [localhost] => (item=/etc/dnsmasq.conf)
> changed: [localhost] => (item=/etc/hosts)
> changed: [localhost] => (item=/etc/pulse/system.pa)
> changed: [localhost] => (item=/etc/rc.local)
> changed: [localhost] => (item=/etc/sudoers)
> changed: [localhost] => (item=/etc/sysctl.conf)
> changed: [localhost] => (item=/etc/hostname)
> changed: [localhost] => (item=/etc/fstab)
> 
> TASK [Check if any xsessions are present] **************************************
> ok: [localhost]
> 
> TASK [Screen visualization: Force hdmi hotplug] ********************************
> skipping: [localhost]
> 
> TASK [Screen visualization: Rendering privileges] ******************************
> skipping: [localhost]
> 
> TASK [Screen visualization: Start X on boot: xinit service] ********************
> skipping: [localhost]
> 
> TASK [Screen visualization: Start X on boot: enable xinit] *********************
> skipping: [localhost]
> 
> TASK [Screen visualization: X privileges: get home] ****************************
> skipping: [localhost]
> 
> TASK [Screen visualization: X privileges: xhost] *******************************
> skipping: [localhost]
> 
> TASK [Screen visualization: X privileges: .xsessionrc] *************************
> skipping: [localhost]
> 
> TASK [LED visualization: i2c] **************************************************
> skipping: [localhost]
> 
> TASK [LED visualization: spi] **************************************************
> skipping: [localhost]
> 
> TASK [LED visualization: Core frequency: core_freq] ****************************
> skipping: [localhost]
> 
> TASK [LED visualization: Core frequency: core_freq_min] ************************
> skipping: [localhost]
> 
> TASK [LED visualization: Core frequency] ***************************************
> skipping: [localhost]
> 
> TASK [pulseaudio: service] *****************************************************
> ok: [localhost]
> 
> TASK [pulseaudio: disable timer based scheduling] ******************************
> ok: [localhost]
> 
> TASK [pulseaudio: config] ******************************************************
> ok: [localhost]
> 
> TASK [pulseaudio: Add virtual cava sink] ***************************************
> skipping: [localhost]
> 
> TASK [mopidy config skeleton] **************************************************
> changed: [localhost]
> 
> TASK [Set max volume to 100%] **************************************************
> changed: [localhost] => (item=amixer -q -c 0 sset HDMI 100%)
> changed: [localhost] => (item=amixer -q -c 0 sset Headphone 100%)
> changed: [localhost] => (item=amixer -q -c 1 sset Headphone 100%)
> changed: [localhost] => (item=amixer -q -c 1 sset Speaker 100%)
> changed: [localhost] => (item=amixer -q -c 2 sset Speaker 100%)
> 
> TASK [Cache directory: Create cache directory] *********************************
> skipping: [localhost]
> 
> TASK [Cache directory: Set cache directory path] *******************************
> skipping: [localhost]
> 
> TASK [Cache medium: get www-data uid] ******************************************
> skipping: [localhost]
> 
> TASK [Cache medium: get www-data gid] ******************************************
> skipping: [localhost]
> 
> TASK [Cache medium: Automount cache medium] ************************************
> skipping: [localhost]
> 
> TASK [Cache medium: Create cache directory] ************************************
> skipping: [localhost]
> 
> TASK [Cache medium: Set cache directory path] **********************************
> skipping: [localhost]
> 
> TASK [Led permissions for www-data] ********************************************
> skipping: [localhost]
> 
> TASK [Audio permissions for www-data] ******************************************
> ok: [localhost]
> 
> TASK [Bluetooth permissions for www-data] **************************************
> ok: [localhost]
> 
> TASK [Bluetooth permissions for pulse] *****************************************
> ok: [localhost]
> 
> TASK [Cache directory access permissions for mopidy] ***************************
> ok: [localhost]
> 
> TASK [www-data home permissions] ***********************************************
> ok: [localhost]
> 
> TASK [www-data raveberry directory permissions] ********************************
> changed: [localhost]
> 
> TASK [Allow www-data passwordless sudo to system scripts] **********************
> ok: [localhost]
> 
> TASK [Enable and restart pulseaudio] *******************************************
> changed: [localhost]
> 
> TASK [Periodic youtube-dl updates] *********************************************
> ok: [localhost]
> 
> TASK [Periodic backup script] **************************************************
> skipping: [localhost]
> 
> TASK [Create raveberry user] ***************************************************
> ok: [localhost]
> 
> TASK [Create raveberry database] ***********************************************
> ok: [localhost]
> 
> TASK [Prepare database: Apply migrations] **************************************
> skipping: [localhost]
> 
> TASK [Prepare database: Create users] ******************************************
> skipping: [localhost]
> 
> TASK [Prepare database: Initialize search engine] ******************************
> skipping: [localhost] => (item=migrate) 
> skipping: [localhost] => (item=installwatson) 
> skipping: [localhost] => (item=buildwatson) 
> 
> TASK [Restore backup: Stop daphne] *********************************************
> skipping: [localhost]
> 
> TASK [Restore backup: Backup old database] *************************************
> skipping: [localhost]
> 
> TASK [Restore backup: Delete old database] *************************************
> skipping: [localhost]
> 
> TASK [Restore backup: Create new database] *************************************
> skipping: [localhost]
> 
> TASK [Restore backup: Copy database backup to target] **************************
> skipping: [localhost]
> 
> TASK [Restore backup: Restore backup] ******************************************
> skipping: [localhost]
> 
> TASK [Migrate database] ********************************************************
> changed: [localhost]
> 
> TASK [Get credentials] *********************************************************
> changed: [localhost]
> 
> TASK [Set output] **************************************************************
> changed: [localhost]
> 
> TASK [Enable and restart mopidy] ***********************************************
> changed: [localhost]
> 
> TASK [Set hostname: Set hostname] **********************************************
> ok: [localhost]
> 
> TASK [Set hostname: Set /etc/hosts] ********************************************
> ok: [localhost]
> 
> TASK [Remove unused system scripts] ********************************************
> changed: [localhost] => (item=/usr/local/sbin/raveberry/enable_tunneling)
> changed: [localhost] => (item=/usr/local/sbin/raveberry/disable_tunneling)
> changed: [localhost] => (item=/usr/local/sbin/raveberry/enable_hotspot)
> changed: [localhost] => (item=/usr/local/sbin/raveberry/disable_hotspot)
> changed: [localhost] => (item=/usr/local/sbin/raveberry/enable_homewifi)
> changed: [localhost] => (item=/usr/local/sbin/raveberry/disable_homewifi)
> 
> TASK [Check if dhcpcd.conf is present] *****************************************
> ok: [localhost]
> 
> TASK [Configure hotspot: dhcpcd] ***********************************************
> skipping: [localhost]
> 
> TASK [Configure hotspot: dnsmasq conf] *****************************************
> skipping: [localhost]
> 
> TASK [Configure hotspot: dnsmasq host] *****************************************
> skipping: [localhost]
> 
> TASK [Configure hotspot: dnsmasq remote url] ***********************************
> skipping: [localhost]
> 
> TASK [Configure hotspot: hostapd protected] ************************************
> skipping: [localhost]
> 
> TASK [Configure hotspot: hostapd unprotected] **********************************
> skipping: [localhost]
> 
> TASK [Configure hotspot: hostapd config] ***************************************
> skipping: [localhost]
> 
> TASK [Configure hotspot: homewifi ssid] ****************************************
> skipping: [localhost]
> 
> TASK [Configure hotspot: homewifi service] *************************************
> skipping: [localhost]
> 
> TASK [Configure hotspot: homewifi script] **************************************
> skipping: [localhost]
> 
> TASK [Configure hotspot: enable homewifi] **************************************
> skipping: [localhost]
> 
> TASK [Configure hotspot: Configure forwarding] *********************************
> skipping: [localhost]
> 
> TASK [Configure hotspot: Enable forwarding] ************************************
> skipping: [localhost]
> 
> TASK [Configure hotspot: Persist forwarding] ***********************************
> skipping: [localhost]
> 
> TASK [Configure hotspot: Replace interface names in system scripts] ************
> skipping: [localhost] => (item=/usr/local/sbin/raveberry/connect_to_wifi) 
> skipping: [localhost] => (item=/usr/local/sbin/raveberry/list_available_ssids) 
> 
> TASK [Configure hotspot: Unblock wlan] *****************************************
> skipping: [localhost]
> 
> TASK [Configure hotspot: Restart dhcpcd] ***************************************
> skipping: [localhost]
> 
> TASK [Configure hotspot: Restart hostapd] **************************************
> skipping: [localhost]
> 
> TASK [Configure hotspot: Restart dnsmasq] **************************************
> skipping: [localhost]
> 
> TASK [Configure hotspot: Disable hotspot at home] ******************************
> skipping: [localhost]
> 
> TASK [Remove default nginx config] *********************************************
> ok: [localhost]
> 
> TASK [events nginx config] *****************************************************
> ok: [localhost]
> 
> TASK [static nginx config] *****************************************************
> ok: [localhost]
> 
> TASK [daphne service] **********************************************************
> ok: [localhost]
> 
> TASK [gunicorn service] ********************************************************
> ok: [localhost]
> 
> TASK [upgrade service] *********************************************************
> ok: [localhost]
> 
> TASK [Configure remote connection: remote service] *****************************
> skipping: [localhost]
> 
> TASK [Configure remote connection: remote connect script] **********************
> skipping: [localhost]
> 
> TASK [Configure remote connection: Create .ssh folder for root] ****************
> skipping: [localhost]
> 
> TASK [Configure remote connection: Check if remote key is present] *************
> skipping: [localhost]
> 
> TASK [Configure remote connection: Copy ssh key] *******************************
> skipping: [localhost]
> 
> TASK [Configure remote connection: Create known hosts file] ********************
> skipping: [localhost]
> 
> TASK [Configure remote connection: Check if key for remote host exists] ********
> skipping: [localhost]
> 
> TASK [Gather ssh keys] *********************************************************
> skipping: [localhost]
> 
> TASK [Add keys to known hosts] *************************************************
> skipping: [localhost]
> 
> TASK [Reload systemd daemon config] ********************************************
> ok: [localhost]
> 
> TASK [Start the server] ********************************************************
> changed: [localhost]
> 
> PLAY RECAP *********************************************************************
> localhost                  : ok=56   changed=14   unreachable=0    failed=0    skipped=77   rescued=0    ignored=0   
> 
> 
>     Finished!
> 
>     Raveberry was successfully installed.
>     You can now visit http://raveberry/
>

**Comment by movioli** [comment]
So i did a new install on a Raspberry Pi3 B+ with the latest version of raspian. still no error during install. but i got these two warning, The login as admin, mod etc. is still not working

> TASK [Create raveberry user] *****************************************************************************************************************************************************************************************************************
> [WARNING]: Module remote_tmp /var/lib/postgresql/.ansible/tmp did not exist and was created with a mode of 0700, this may cause issues when running as another user. To avoid this, create the remote_tmp dir with the correct permissions
> manually
> changed: [localhost]
> 
> TASK [Create raveberry database] *************************************************************************************************************************************************************************************************************
> changed: [localhost]
> 
> TASK [Prepare database: Apply migrations] ****************************************************************************************************************************************************************************************************
> [WARNING]: Module remote_tmp /var/www/.ansible/tmp did not exist and was created with a mode of 0700, this may cause issues when running as another user. To avoid this, create the remote_tmp dir with the correct permissions manually
> changed: [localhost]

**Comment by movioli** [comment]
Hello i think i found the issue.  all is explained in this post

> https://stackoverflow.com/questions/38807296/django-1-9-2-assertionerror-database-connection-isnt-set-to-utc

a quick fix for me was to change /home/pi/.local/lib/python3.7/site-packages/raveberry/main/settings.py the Line 

`USE_TZ from true to false. `

**Comment by raveberry** [comment]
oh, wow!
Great on catching that, thanks a lot. Happy that it works for you now.

It seems like this is a [known issue for psycopg2](https://github.com/psycopg/psycopg2/issues/1293) under django 2.2, I'm going to pin that version in the next release.
Also, apparently I hardcoded a (my) timezone in the settings file, I should change that as well.

**Comment by movioli** [comment]
thx for that. Keep up the great work:)
