### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by avidsapp** [raveberry/raveberry#121]
My use case requires arm64 support. I will try for a PR shortly, unless you beat me to it.

**Comment by raveberry** [comment]
Maybe I was a little too confident. I just tried building the images for arm64, and as it turns out, libspotify never [existed for arm64](https://github.com/mopidy/libspotify-archive).
May I ask what you need this for? I might be able to provide an image for arm64 without Spotify support, but it would require some conditional configuration.

**Comment by avidsapp** [comment]
Drop-in to an [arm64 docker server](https://github.com/avidsapp/rpi-docker-server) on RPi 4 (8GB) and Ubuntu 20 or 21. Spotify is somewhat crucial. I was gonna go with a spotifyd and tui combo, but raveberry with icecast looks ideal.

**Comment by avidsapp** [comment]
I'm using the `docker-compose.yml` method. Adding `platform: linux/amd64` to these images allows it to spin up, but produces
```
mopidy_1  | standard_init_linux.go:228: exec user process caused: exec format error
```
errors for each of these containers in the `docker-compose logs`

**Comment by raveberry** [comment]
I'm afraid you won't be able to use Spotify with Raveberry in this configuration, then.
libspotify is necessary to play Spotify songs with mopidy. The library has been deprecated for years, so there will never be a version for arm64, probably.

So you either need to use a different Spotify playback solution ([librespot](https://github.com/librespot-org/librespot) for example) and drop Raveberry or use a 32bit operating system, e.g. Raspberry Pi OS.

**Comment by avidsapp** [comment]
Thanks. I appreciate you looking into it. I'd rather not drop Raveberry, so an additional RPi Zero should suffice.
