### ISSUE TITLE
stuck with a spotify song in red letters

### ISSUE THREAD

**Issue by copykatze** [raveberry/raveberry#124]
Hi, I have a strange problem: I am stuck with a song that is displayed in red letters and nothing I do could remove it so far. 

I tried 
- skipping it
- downvoting it to -2 (where it should be kicked)
- deleting the playlist (works for the rest of the playlist, but not for the song that is stuck)
- restarting the service
- rebooting the whole system
- updating (from 0.9.5 to 0.9.8)

Now I run out of ideas...

**Comment by copykatze** [comment]
I was able to log into the django admin interface (/admin) and delete it form the current songs playlist. That fixed it :)

**Comment by raveberry** [comment]
Great that you could fix it. Deleting the current song is sometimes necessary to recover from desyncs.
The /settings page already has a button to do that in the "Sound Output" section, the next time you don't need to go through the admin page.
