### ISSUE TITLE
Configure CI

### ISSUE THREAD

**Issue by 8sd** [raveberry/raveberry#13]
Use CI for testing and publishing releases to PiPy

**Comment by raveberry** [comment]
After trying to make travis install mopidy on Ubuntu 18.04 for a long time, I decided to wait with this until travis offers a Ubuntu 20.04 environment

**Comment by raveberry** [comment]
As travis will probably not offer Ubuntu 20.04 for longer, a solution using docker was implemented in b2a640a.
