### ISSUE TITLE
Migrate to Django 3

### ISSUE THREAD

**Issue by 8sd** [raveberry/raveberry#15]
https://www.djangoproject.com/weblog/2019/dec/02/django-3-released/

**Comment by raveberry** [comment]
Django 3.0 is not an LTS version and introduces some breaking changes (at least the last time I tried to upgrade). We will stick to Django 2.2 until Django 3.2 comes around next year.
Although integrated asgi support is a nice thing, I don't know if it can offer all functionality channels is providing right now. Will have to find that out.
