### ISSUE TITLE
Song plays from the beginning after a restart of the server instead of starting from the position from before

### ISSUE THREAD

**Issue by 8sd** [raveberry/raveberry#16]
After restarting the raveberry-server the songs starts to play from the beginning.
After some time the song skips to the position where it was stopped.
This could be fixed by setting the volume to 0 until seeking to the correct position.

**Comment by nickatnight** [comment]
Are you guys accepting PRs?

**Comment by raveberry** [comment]
Yeah, sure!

**Comment by raveberry** [comment]
I did not observe this issue for a long time, so I'm going to assume that some update fixed it.
If it surfaces again, feel free to reopen.
