### ISSUE TITLE
Support Playback of Local Files

### ISSUE THREAD

**Issue by raveberry** [raveberry/raveberry#20]
Mopidy can play files from the local filesystem, so support a local music library.
Add an option to specify a folder containing the desired music and add it during installation.
Make it modifiable at least via cli, possibly a dedicated script to parse folders.
Songs will be added into the database with their filepath as key.

**Comment by nickatnight** [comment]
This is great 👌

**Comment by 1r00t** [comment]
+1

**Comment by raveberry** [comment]
Implemented in c402f25. Let me know how you like it!
