### ISSUE TITLE
debug server

### ISSUE THREAD

**Issue by smypm** [raveberry/raveberry#21]
my raveberry will not chage rom debug server, or atleast  think so, cuz i keep getting that message everytime i starrt it. and i cant figure out how to get cava working either.
might just be me being stupid  xD

**Comment by raveberry** [comment]
Are you always starting your instance with `raveberry run`?
If so, you will always start the debug server.
To use the production server you need to install Raveberry system wide using `raveberry system-install`.
cava will then be available in your full installation.
The reasoning for this is that all visualizations require some kind of privileged operation, so they are not available in user mode.

**Comment by smypm** [comment]
So how do I run it in the other mode when its installed?

**Comment by raveberry** [comment]
If installation completed successfully it should automatically be running at port 80.
You can check the status of the server using `sudo systemctl status daphne`. For further debugging information take a look at [this debug document](https://github.com/raveberry/raveberry/blob/master/docs/debug.md), and let me know if something is missing.

**Comment by smypm** [comment]
okey, its starting atleast :D im just stupid and did not notice hehe...
but how do i manage to get cava working?

**Comment by raveberry** [comment]
cava is the tool I use to provide frequency information for all visualizations (leds and the screen visualizer)
It will automatically be installed if you enabled at least one of the two visualizations in your config file before installation. Note that you need a Raspberry Pi 4 for the screen visualizer, the RPi3's GPU does not suffice.
If you did that you should be able to enable the visualization in `http://raveberry/lights` (if you are logged in).

**Comment by smypm** [comment]
ah ok, then i cant im on 3, but thansk for all the help anyway :D
