### ISSUE TITLE
Cant configure hotspot

### ISSUE THREAD

**Issue by stappjno** [raveberry/raveberry#27]
If server is running, a click on "Enable hotspot" does not toggle the boolean / has no effect.

**Comment by raveberry** [comment]
Did you set `hotspot = True` before performing the installation?
If no, reinstall Raveberry with this value and those in the [Hotspot] section set.
If yes, please check the log of `daphne` and `hostapd`.

**Comment by stappjno** [comment]
I have not set hotspot to true before install but I thought that if I see a setting for hotspot where I can enable/disable it, it will enable/disable it. It was a bit misleading that the green tick showed up when I click on "Enable hotspot". Maybe we could add some tooltips to describe all the functions on the settings page a bit more.

Can I change the settings in /opt/raveberry/config/raveberry.ini and re-run the system-install command? And is it possible to use this setting without having a second wifi network adapter? For example if I have a home wifi configured called "home" and the raspi boots up and detects there is no wifi called "home" it would start his own hotspot.

**Comment by raveberry** [comment]
I admit that the UI is a little misleading. The admin page was mainly built for functionality, but I could definitely build in some more information about which options are available. This would also help for the user version and the docker setup, where not everything in the settings is active.

You can do a reinstall with the hotspot enabled. The config file you need to change is the one that `raveberry system-install` is asking you to confirm. If you don't supply a `db_backup`, your database will be kept.

If you only have one wifi device, it will always create a hotspot. The second interface is used for internet connection. It is probably possible to make the homewifi feature work like you described, but currently it only works on the second device.
For testing I recommend an ethernet cable or a local session on the raspberry.

**Comment by stappjno** [comment]
Ok i'll try that. Maybe I'll add an USB-Wifi-Adapter to the setup.
