### ISSUE TITLE
Add a setting to keep downloaded tracks from youtube

### ISSUE THREAD

**Issue by stappjno** [raveberry/raveberry#28]
As a feature request

**Comment by raveberry** [comment]
By default, songs from youtube should remain on disk until they are manually deleted. Were they removed in your case?

**Comment by stappjno** [comment]
I dont know. I expected them to be in /home/pi/Music (comment in raveberry.ini, default cache directory) but this dir does not exist.

**Comment by raveberry** [comment]
It defaults to `~/Music/raveberry` of the user that is running the process. If you are using the system version, this will be `www-data` with the home located at `/var/www`. So the downloaded songs might be there.

**Comment by stappjno** [comment]
Great, thank you! The files are where you said. Maybe this could be a problem in the future if someone is using a pi with just 4GB of space and does not know about this. But this is something for another issue ;)
