### ISSUE TITLE
Add a setting to disable youtube at all

### ISSUE THREAD

**Issue by stappjno** [raveberry/raveberry#29]
Feature request

**Comment by raveberry** [comment]
Could you give a little more detail how you would imagine this?
Right now, Youtube is always enabled to act as a fallback if Spotify could not find the query. Did this lead to unwanted songs being enqueued in your case?

**Comment by stappjno** [comment]
I use raveberry on a pi4 with my local music library over usb. If I search for a song, there is my version and sometimes a youtube-version and the youtube-version has often no clear start / ending and is not optimal for a party playlist. If I could disable yt there would be just my music library and no chance to get bad quality songs.

**Comment by raveberry** [comment]
Alright, I get that. Sounds like a sensible feature, I will probably implement that.
Thanks for the suggestion!

**Comment by raveberry** [comment]
This is now an option in the settings with be2a408c3da2e0d71234a80706ed174151391809 in version 0.5.5
