### ISSUE TITLE
Change the alarm sound

### ISSUE THREAD

**Issue by romanpeters** [raveberry/raveberry#31]
Where can I find the `alarm.mp3` sound file? I'd like to use my own custom sound.

**Comment by raveberry** [comment]
It's located at `/opt/raveberry/config/sounds/alarm.m4a`. If you want to use an mp3 file, either convert it or change [this line](https://github.com/raveberry/raveberry/blob/master/core/musiq/player.py#L299) in `core/musiq/player.py` accordingly.

**Comment by romanpeters** [comment]
Thanks! 😊
