### ISSUE TITLE
Playlists and Robot Head not working

### ISSUE THREAD

**Issue by MickyGX** [raveberry/raveberry#36]
When I enable playlist (icon next to dice) it finds a playlist and when i click it it says queuing but never adds it to list. Also when I enable playlists and press the robot head to get a suggestion i get 'Getting radio info' overlayed by Server Error (500) see picture:
![image](https://user-images.githubusercontent.com/1932078/81343945-841b9a00-907b-11ea-89b8-1e25616b299d.png)

**Comment by raveberry** [comment]
What do your logs say? With v0.5.7 there should finally be sensible logs.
In your docker setup you can access them with `docker-compose -f icecast.docker-compose.yml logs daphne`

**Comment by MickyGX** [comment]
![image](https://user-images.githubusercontent.com/1932078/81397420-e52f8600-90ec-11ea-9739-8bcd7acc6bf3.png)
Thats all it says. As for the song cache I have that enabled and it seems to be working as its putting files in their when I listen to something off youtube

**Comment by MickyGX** [comment]
So I updated raveberry to check out the headphones link and it seems the playlist feature is working. Not sure if a restart sorted it or the new release but it's working now

**Comment by raveberry** [comment]
This might have been an issue with Youtube itself, which returned unexpected content, causing an error I didn't catch. I will add updating `youtube-dl` in every new docker build, so this shouldn't happen as much.
