### ISSUE TITLE
Spotify Error: Unsupported URL:

### ISSUE THREAD

**Issue by MickyGX** [raveberry/raveberry#38]
Getting the following whenever I try to stream anything from Spotify:

![image](https://user-images.githubusercontent.com/1932078/81426190-7703b700-911e-11ea-9f74-efb5d3bbf485.png)

This was working fine but not sure what changed. I did update to latest version but I was sure this was working after that. I've re authorized mopidy with spotify and still the same

**Comment by raveberry** [comment]
Probably this url was handled by `youtube-dl` which returns this error if given a spotify link (understandably). In the dropdown you can choose whether to use spotify or youtube. Also, did you also provide your credentials in the settings page and make sure they are correct? Raveberry needs the client id and secret as well to make some API calls.

**Comment by MickyGX** [comment]
Spotify credentials entered in mopidy.conf and into raveberry spotify section. Spotify selected and picked a song with spotify logo:

![image](https://user-images.githubusercontent.com/1932078/81479379-759ec100-91e8-11ea-9dfe-8a38812bfc89.png)

Still get same so I disabled youtube in settings and now get this:

![image](https://user-images.githubusercontent.com/1932078/81479412-a121ab80-91e8-11ea-8f4a-6e1ecc3de9be.png)

Other than putting the credentials in mopidy is there something else I should be enabling? Like I said before this was working fine at first.

To authenticate mopidy i went to https://mopidy.com/ext/spotify/#authentication and copied and pasted the info into the conf and into the settings page and redid it again just to be double sure

**Comment by raveberry** [comment]
Can you confirm that Mopidy successfully logs into Spotify?
You can check its logs with `docker-compose -f <your compose.yml> logs mopidy`
Maybe there is an error during authentication. Otherwise there might be a problem on Raveberry's side when it checks for the song before playing it, but I could not reproduce this right now.

**Comment by MickyGX** [comment]
So I got to the bottom of it. When I checked my logs it was disabling the spotify plugin. So I double checked my compose file and found it mopidy was pointing to mopidy.conf not mopidy_icecast.conf.

It needs updating in the docker compose file as its default is mopidy.conf:

  mopidy:
    image: raveberry/raveberry-mopidy
    volumes:
      - songs-cache:/Music/raveberry
      # If you want to use spotify, 
      # uncomment this line with a path to a config file containing the spotify credentials
      # - /path/to/mopidy.conf:/config/**mopidy.conf**
    command: bash -c "/usr/bin/mopidy --config /config/**mopidy_icecast.conf**"

**Comment by raveberry** [comment]
Oh, right. The mopidy container uses a different config when streaming. Thanks for pointing it out, I changed the comment in the compose file with 3261078bb5fe5dd4ab4f736b587da9ab962236f3.

**Comment by linuxundich** [comment]
I just installed raveberry on a rpi3. I still get the same error when iItry to play a spotify song:


error.log
```
2020-05-14 16:01:11 youtube.error:79 ERROR  ERROR: Unsupported URL: https://open.spotify.com/embed/track/3JOVTQ5h8HGFnDdp4VT3MP
2020-05-14 16:06:43 youtube.error:79 ERROR  ERROR: Unsupported URL: https://open.spotify.com/embed/track/3ZFTkvIE7kyPt6Nu3PEa7V
```

info.log
```
(2020-05-14 16:09:24 youtube.error:79 ERROR  ERROR: Unsupported URL: https://open.spotify.com/embed/track/3ZFTkvIE7kyPt6Nu3PEa7V
2020-05-14 16:09:24 log.log_response:228 WARNING  Bad Request: /ajax/musiq/request_music/
2020-05-14 16:10:15 youtube.error:79 ERROR  ERROR: Unsupported URL: https://open.spotify.com/embed/track/3ZFTkvIE7kyPt6Nu3PEa7V
2020-05-14 16:10:15 log.log_response:228 WARNING  Bad Request: /ajax/musiq/request_music/
```

**Comment by raveberry** [comment]
Did you make sure to choose the Spotify icon in the dropdown?
Otherwise, all your requests will be handled by the Youtube backend, which can not deal with Spotify links.

**Comment by linuxundich** [comment]
Yep, i think so...

![raveberry-spotify1](https://user-images.githubusercontent.com/1716643/81947565-00c0f200-9601-11ea-8264-456f8d3ee5cd.png)

![raveberry-spotify2](https://user-images.githubusercontent.com/1716643/81947601-09192d00-9601-11ea-9984-a36fb8bad5d7.png)

![raveberry-spotify3](https://user-images.githubusercontent.com/1716643/81947612-0c141d80-9601-11ea-9de7-108244651c0b.png)

**Comment by raveberry** [comment]
Alright, if that selection is shown, Raveberry has valid Spotify credentials. The url is only passed to the Youtube backend as a fallback if there was an error with the Spotify backend. Did mopidy successfully login to Spotify?
`journalctl -xe -u mopidy` should show something like this:
```
[SpotifyEventLoop] mopidy_spotify.backend Logged in to Spotify in online mode
[SpotifyBackend-7] mopidy_spotify.web Logged into Spotify Web API as <user>
```

**Comment by linuxundich** [comment]
Ok, i think we found the problem. I don't have this output. My log shows this:

```
May 14 15:08:50 raveberry mopidy[511]: WARNING  [MainThread] mopidy.config Ignoring config section 'spotify' because no matching extension was found
```

**Comment by raveberry** [comment]
Great, this should be an easy fix, just install `mopidy-spotify`.
Apparently this package is not installed during setup, I will add it.
Thanks for bringing it up!

**Comment by linuxundich** [comment]
Yep, solved! Thanks.

**Comment by raveberry** [comment]
With 0.6.0, new installs will install this package automatically.

**Comment by MickyGX** [comment]
I have just updated Raveberry to the latest release doing a completely fresh install including all dependencies i.e. stopping and removing containers and images. When I enter my Spotify credentials it appears to work fine and get a green notification at the bottom of the screen but when I goto to the musiq page Spotify icon isn't there and when searching for any song Spotify choice does not appear on the list. Checking my logs I get the following:

`2020-05-22 11:10:35 settings.state_dict:167 INFO  scripts not installed
2020-05-22 11:11:16 settings.state_dict:167 INFO  scripts not installed`

I checked Mopidy and it is logging in fine:

`mopidy_1            |   Logged into Spotify Web API as wdfy8t64wpukroe31o13i5qm0
mopidy_1            | INFO     2020-05-22 04:06:06,494 [6:SpotifyBackend-6] mopidy_spotify.backend                                             
mopidy_1            |   Spotify private session activated
`

When I go back to settings Spotify credentials are blan the and the enabled tick is removed.

**Comment by raveberry** [comment]
The problem is probably that Raveberry still uses old static files so the enable button doesn't actually do anything.
To fix this you need to remove the corresponding volume. List all your volumes with `docker volume ls` and then delete the one with the name containing `static-files` (e.g. `docker volume rm raveberry_static-files`). You might need to stop/remove containers that are currently using it.

The reason for this is that the javascript code is compressed to a file the first time it is accessed. This file is then shared with the ngnix container so it can be served. If the code changes, the compressed file is somehow not updated, so this manual deletion is required.

**Comment by MickyGX** [comment]
Thanks for the quick response, that did the trick!
