### ISSUE TITLE
Path to local library doesn't get saved

### ISSUE THREAD

**Issue by linuxundich** [raveberry/raveberry#46]
I justed installed a fresh instance of waveberry. Every time I open the settings page, the path to the local library is set to / instead of the folder I entered before.

**Comment by mageunic** [comment]
I have the same problem than you. I'll try to look in the configuration documents to see if we can modify.

**Comment by mageunic** [comment]
Currently, you must enter the path to the local folder and then run a scan so that your music in this folder is taken into account. If you add new audio files you will have to rescan the folder.

**Comment by raveberry** [comment]
> Currently, you must enter the path to the local folder and then run a scan so that your music in this folder is taken into account. If you add new audio files you will have to rescan the folder. To listen to the audio files you write their name in the search bar and they will appear.

That's exactly how it works. Rescanning for new files should not take too long, as it will skip files that have already been scanned.
I just implemented that the current library path is shown in the settings if it was already set. This will be in the next update, hope this makes the interface a little clearer.

**Comment by raveberry** [comment]
This feature was integrated with v0.6.0.
