### ISSUE TITLE
Show installed version in settings

### ISSUE THREAD

**Issue by Vanixxx** [raveberry/raveberry#48]
(Maybe an update function in settings)

**Comment by raveberry** [comment]
I actually implemented this yesterday and it will be included in the next version. 
The update-button is a nice feature, will probably add that as well.
Currently I'm working on the auto-upvoting though ;)

**Comment by raveberry** [comment]
Since 0.6.4 there is an 'About' section in the settings. It shows the currently installed version as well as the latest version available.
Additionally, there is a button that upgrades the system instance to the newest version.
