### ISSUE TITLE
Appears To Be Constantly Downloading But Not The Case

### ISSUE THREAD

**Issue by MickyGX** [raveberry/raveberry#49]
On latest version I've noticed the download arrow animation is constantly showing as downloading on local and YouTube files but the songs play fine:

![image](https://user-images.githubusercontent.com/1932078/82656311-2a71ae80-9be9-11ea-8d7d-9e1a6ca48ec4.png)

Nothing in logs to indicate an error

**Comment by raveberry** [comment]
This might be a purely front-end related issue, please try if https://github.com/raveberry/raveberry/issues/38#issuecomment-632609708 fixes this.

**Comment by MickyGX** [comment]
Thanks again, this is working correctly now!

**Comment by raveberry** [comment]
Great, I will add it to the readme.
