### ISSUE TITLE
Feature request: Setting for choosing how many results to show

### ISSUE THREAD

**Issue by MatthewAscough** [raveberry/raveberry#52]
Since the recent update we no only get one search result per service - it would be nice to have a setting to choose how many results to show per service ie 4 for Spotify and 1 for YouTube.
Furthermore it'd be useful if when searching you could choose a specific service to search that it then shows say 8 results for.

**Comment by raveberry** [comment]
Yeah, sure. It should be easy to add that feature.

I want to briefly explain my reasoning for the previous change. On my install, people rely a lot on the archived songs for requesting music. If there are three services active, two suggestions per service would make scrolling necessary to reach these local entries. So I lowered the number of online suggestions to one per service (or two if only one service is active).

Adding this option will make it possible to lower the number of suggestions for such use cases and increase them for others. There will probably be an input field for every service that determines the amount of suggestions shown for that service, defaulting to two.

So thanks for the request, I will add this soon.

**Comment by raveberry** [comment]
Implemented in 2048bde.
Also, it is now possible to change the number of offline suggestions as well.
