### ISSUE TITLE
Volume changes only affect output, not cava

### ISSUE THREAD

**Issue by 8sd** [raveberry/raveberry#6]
When changing the volume on the web page both the audio output and the volume for cava (animation) are changed.
Thus the effects of cava are influenced by the volume settings.

**Comment by raveberry** [comment]
Fixed in 5eb47b554e3cfedbbf44dcf303c4716c5892977d. Raveberry now tries to change pulseaudio's volume first before resorting to changing mopidy's volume. This way visualization can work with full volume while the speaker output is at the specified volume.
