### ISSUE TITLE
Deezer Support

### ISSUE THREAD

**Issue by MickyGX** [raveberry/raveberry#61]
I came across Deezloader recently which allows you to download music from Deezer.com without a subscription, you just need a regular free account. I wondered if this could be added as a source along with Spotify and Soundcloud? https://gist.github.com/duttaditya18/f366c7694fe50d7c69f8654579112da5

**Comment by raveberry** [comment]
Mopidy once had a Deezer plugin, but [it got removed](https://discourse.mopidy.com/t/deezer-extension-removed/2233). Apparently, Deezer is not happy with third-party tools.

Accordingly, it will not be integrated into Raveberry either, sorry.

**Comment by MickyGX** [comment]
No problem. Thanks for replying
