### ISSUE TITLE
Feature request: Show connected SSID and IP

### ISSUE THREAD

**Issue by copykatze** [raveberry/raveberry#63]
I have a touch display hooked up to the pi, serving as another client (using chromium with a software keyboard plugin). The raveberry is used in different free wifi networks that don't always provide hostname lookup (or however that might be called correctly). Thus, I need to scan the network for the raveberrys IP after startup and provide it to the users.
It would be very convenient to have the possibility to view the currently connected network SSID and the machines IP at the web UI. Even better: show as a barcode for the users to join without needing to type an URL. I understand this is a specific use case, so this should be toggeled in the admin settings.
I might as well try to solve this myself, but since I am not very experienced, so I would probably need help.

**Comment by raveberry** [comment]
I like the idea!

I would probably create something like `http://raveberry/qr`, a new page that you could open on your touch display. There I would  show information about the IP address of Raveberry and the SSID it is connected to.
On the top I would show a qr code pointing to `http://<ip>/`.
So you could open `http://localhost/qr` on your touchpad without information about the ip and it would show it to you.

I could probably create a qr code that connects people to the network as well. After all, Raveberry knows the SSID and the password of the network, if it is connected to it. However, everybody with access to the page could then find out the password, which might not be desirable.

What do you think?

**Comment by copykatze** [comment]
Great! For my usecase it would be neccessary to have a link to http://localhost/qr that is accessable from /musiq for a non logged in user, since my touch display is a "guest" in the chromium kiosk view and cannot enter a URL to the browser. But that link I would probably be able to add to my local system with my limited django skills, in case you don't want to add another link on the page.

My thoughts on the network credentials via QR: That would be awesome!
I share the concerns, there might be situations where the network credentials should not be public, so it would be nice to be able to toggle this network QR in the admin settings. For me, this would not matter though, since the system would only be operated within networks that are public to its users.

**Comment by raveberry** [comment]
Included in 0.6.15.
The page is linked from the dropdown, but you need to be logged in so you can access it, since it reveals potentially sensitive information.
Here is a screenshot:
![NetworkInfo](https://user-images.githubusercontent.com/53476237/87724701-2ebae200-c7bc-11ea-85de-ce647253200b.png)
