### ISSUE TITLE
Question: How to update code changes in container?

### ISSUE THREAD

**Issue by copykatze** [raveberry/raveberry#64]
I would like to try to change some things and play with the code. More to learn from it than to expect big improvements, as I am not very experienced.

I found the "Quick start for contributors", but that did not really work for me or I don't understand how to make it work on macOS. I thought I need to fork the project, clone it to my local machine (macOS 10.14.6), make local changes and test them by running the local code in a docker container (docker-compose up -d). But how do I update the code of the container after I changed the code localy? If I just run docker-compose up -d again, it does not seem to be updated.

I found commands how to stop ("docker stop $(docker ps -a -q)")and remove ("docker rm $(docker ps -a -q)") containers, but after running docker-compose up -d, the code still seems not to be updated.

I will keep digging around the net how to do this, but I would rather spend the time coding... so if someone could be so kind and point me in the right direction, I would much appreciate it. Sorry for this noob question... :)

**Comment by raveberry** [comment]
Cool that you want to dig around a little.

For simply trying out changes `raveberry run` is definitely faster. Could be that it does not work on Mac however, due to mopidy dependencies and whatnot (you probably tried it already anyway).

If you need to use docker, you have to build a new container to have your changes reflected. In the docker-compose file you see that the container `raveberry/raveberry` is used. So you either need to overwrite this container or rename the tag in the compose file.

To do the former, take a look at `docker/build.sh`. There you can find all commands to build the various docker images used. Since `raveberry/raveberry` is probably the only thing you need to change, and you don't need to build it for multiple architectures, this command is the one you are looking for:
`docker build -f docker/Dockerfile -t raveberry/raveberry docker/`

This will build a new container with the `raveberry/raveberry` tag and your next `docker-compose up` will use the new code.

**Comment by copykatze** [comment]
Hey thanks for helping me again :)
Yes, I did not get the manual pip install to work and mopidy seems to the problem, even after installing it on the Mac (via brew). 
The docker install worked great and I would not mind waiting for the build when testing new changes.
Now I tried your suggestion, but there seems to be a problem:
```
$ docker build -f docker/Dockerfile -t raveberry/raveberry docker/
Sending build context to Docker daemon  192.5kB
Step 1/8 : FROM raveberry/raveberry-dependencies
latest: Pulling from raveberry/raveberry-dependencies
e9afc4f90ab0: Already exists
989e6b19a265: Already exists
af14b6c2f878: Already exists
5573c4b30949: Already exists
11a88e764313: Already exists
ee776f0e36af: Already exists
513c90a1afc3: Already exists
df9b9e95bdb9: Already exists
86c9edb54464: Already exists
202ac7b62184: Already exists
19df632b11b4: Already exists
498c9853ff62: Already exists
Digest: sha256:24c76cd9540d6524cb5f89314ac9007559a40822cfd5015ec4dd56484b49ed4f
Status: Downloaded newer image for raveberry/raveberry-dependencies:latest
 ---> 2d5e09ff6c46
Step 2/8 : RUN pip install -U youtube-dl &&	rm -rf ~/.cache/pip
 ---> Running in 187fd22dc680
Requirement already up-to-date: youtube-dl in /usr/local/lib/python3.8/site-packages (2020.6.16.1)
Removing intermediate container 187fd22dc680
 ---> b1647d9cd7ab
Step 3/8 : COPY . /opt/raveberry
 ---> e893fd47a69e
Step 4/8 : COPY docker/entrypoint.sh /entrypoint.sh
COPY failed: stat /var/lib/docker/tmp/docker-builder209664216/docker/entrypoint.sh: no such file or directory
```
but that file seems to be at the right place:
```
$ ls docker/entrypoint.sh
docker/entrypoint.sh
```
And I am out of ideas again :/

**Comment by raveberry** [comment]
Woops.
I recently changed the build directory for the container but did not adapt the build.sh.
The correct command is `docker build -f docker/Dockerfile -t raveberry/raveberry .` (a dot instead of `docker/`)

**Comment by copykatze** [comment]
Thanks again, that got me a step ahead, I have an updated image now :)
But unfortunately, the server won't start up now. If I run "docker-compose up" now, this seems to indicate the cause:
```
daphne_1  | Traceback (most recent call last):
daphne_1  |   File "/usr/local/bin/daphne", line 8, in <module>
daphne_1  |     sys.exit(CommandLineInterface.entrypoint())
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/daphne/cli.py", line 191, in entrypoint
daphne_1  |     cls().run(sys.argv[1:])
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/daphne/cli.py", line 252, in run
daphne_1  |     application = import_by_path(args.application)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/daphne/utils.py", line 12, in import_by_path
daphne_1  |     target = importlib.import_module(module_path)
daphne_1  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
daphne_1  |     return _bootstrap._gcd_import(name[level:], package, level)
daphne_1  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
daphne_1  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
daphne_1  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
daphne_1  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
daphne_1  |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
daphne_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
daphne_1  |   File "./main/asgi.py", line 9, in <module>
daphne_1  |     django.setup()
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
daphne_1  |     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in __getattr__
daphne_1  |     self._setup(name)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 66, in _setup
daphne_1  |     self._wrapped = Settings(settings_module)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 157, in __init__
daphne_1  |     mod = importlib.import_module(self.SETTINGS_MODULE)
daphne_1  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
daphne_1  |     return _bootstrap._gcd_import(name[level:], package, level)
daphne_1  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
daphne_1  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
daphne_1  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
daphne_1  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
daphne_1  |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
daphne_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
daphne_1  |   File "./main/settings.py", line 172, in <module>
daphne_1  |     shutil.copytree(
daphne_1  |   File "/usr/local/lib/python3.8/shutil.py", line 554, in copytree
daphne_1  |     return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
daphne_1  |   File "/usr/local/lib/python3.8/shutil.py", line 455, in _copytree
daphne_1  |     os.makedirs(dst, exist_ok=dirs_exist_ok)
daphne_1  |   File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
daphne_1  |     mkdir(name, mode)
daphne_1  | FileExistsError: [Errno 17] File exists: '/opt/raveberry/static/admin'
raveberry_daphne_1 exited with code 1
```
Since I made some code changes, I cloned the original repo again, same result.
So I tried to make it work with docker as I remember how it worked the first time (download the docker-compose.yml to a clean directory and run docker-compose up) - but also the same result. I could imagine that now the same (broken) image is used by docker-compos, but guess I am missing core understanding how docker works to fix this. Maybe docker won't make my life easier afterall and I should check other options...

**Comment by raveberry** [comment]
I'm surprised you ran into this problem.
The error tells you that Raveberry tried to copy a folder to a location that already exists. However, it should only perform the operation if the folder does not already exist. So something in this check has to be broken.
Could it be that you are using an old version of the docker-compose file?

I could not reproduce your issue. Starting from a fresh setup, `docker-compose up` worked. Then I built the raveberry container locally with a change, and the next `docker-compose up` reflected the change.
Maybe you have some old containers/volumes lying around?

**Comment by copykatze** [comment]
Yes, it seems that was the problem.
With "docker images" I found that there were multiple images of raveberry/raveberry, so I removed the container and deleted the images. Afterwards I could have the image and the container rebuild from the new source and it works with the original code. 
Now I made a trivial change and
$ docker rm $(docker ps -a -q)
$ docker rmi raveberry/raveberry
$ docker build -f docker/Dockerfile -t raveberry/raveberry .
$ docker-compose up
but as soon as I try to visit localhost/musiq
```
daphne_1  | Starting: /usr/local/bin/daphne --bind 0.0.0.0 --port 9000 main.asgi:application
daphne_1  | 2020-07-13 15:56:20 log.log_response:222 ERROR  Internal Server Error: /musiq/
daphne_1  | Traceback (most recent call last):
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
daphne_1  |     response = get_response(request)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
daphne_1  |     response = self.process_exception_by_middleware(e, request)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
daphne_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
daphne_1  |   File "./core/musiq/musiq.py", line 243, in index
daphne_1  |     return render(request, "musiq.html", context)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/shortcuts.py", line 36, in render
daphne_1  |     content = loader.render_to_string(template_name, context, request, using=using)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
daphne_1  |     return template.render(context, request)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
daphne_1  |     return self.template.render(context)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 171, in render
daphne_1  |     return self._render(context)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
daphne_1  |     return self.nodelist.render(context)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 937, in render
daphne_1  |     bit = node.render_annotated(context)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
daphne_1  |     return self.render(context)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
daphne_1  |     return compiled_parent._render(context)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
daphne_1  |     return self.nodelist.render(context)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 937, in render
daphne_1  |     bit = node.render_annotated(context)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
daphne_1  |     return self.render(context)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/compressor/templatetags/compress.py", line 143, in render
daphne_1  |     return self.render_compressed(context, self.kind, self.mode, forced=forced)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/compressor/templatetags/compress.py", line 111, in render_compressed
daphne_1  |     cache_key, cache_content = self.render_cached(compressor, kind, mode)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/compressor/templatetags/compress.py", line 89, in render_cached
daphne_1  |     cache_key = get_templatetag_cachekey(compressor, mode, kind)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/compressor/cache.py", line 104, in get_templatetag_cachekey
daphne_1  |     "templatetag.%s.%s.%s" % (compressor.cachekey, mode, kind))
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
daphne_1  |     res = instance.__dict__[self.name] = self.func(instance)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/compressor/base.py", line 200, in cachekey
daphne_1  |     [self.content] + self.mtimes).encode(self.charset), 12)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
daphne_1  |     res = instance.__dict__[self.name] = self.func(instance)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/compressor/base.py", line 194, in mtimes
daphne_1  |     for kind, value, basename, elem in self.split_contents()
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/compressor/js.py", line 17, in split_contents
daphne_1  |     filename = self.get_filename(basename)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/compressor/base.py", line 159, in get_filename
daphne_1  |     raise UncompressableFileError(
daphne_1  | compressor.exceptions.UncompressableFileError: 'libs/jquery/dist/jquery.min.js' could not be found in the COMPRESS_ROOT '/opt/raveberry/static' or with staticfiles.
daphne_1  | 2020-07-13 15:56:22 log.log_response:222 ERROR  Internal Server Error: /musiq/
daphne_1  | Traceback (most recent call last):
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
daphne_1  |     response = get_response(request)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
daphne_1  |     response = self.process_exception_by_middleware(e, request)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
daphne_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
daphne_1  |   File "./core/musiq/musiq.py", line 243, in index
daphne_1  |     return render(request, "musiq.html", context)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/shortcuts.py", line 36, in render
daphne_1  |     content = loader.render_to_string(template_name, context, request, using=using)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
daphne_1  |     return template.render(context, request)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
daphne_1  |     return self.template.render(context)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 171, in render
daphne_1  |     return self._render(context)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
daphne_1  |     return self.nodelist.render(context)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 937, in render
daphne_1  |     bit = node.render_annotated(context)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
daphne_1  |     return self.render(context)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
daphne_1  |     return compiled_parent._render(context)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
daphne_1  |     return self.nodelist.render(context)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 937, in render
daphne_1  |     bit = node.render_annotated(context)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
daphne_1  |     return self.render(context)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/compressor/templatetags/compress.py", line 143, in render
daphne_1  |     return self.render_compressed(context, self.kind, self.mode, forced=forced)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/compressor/templatetags/compress.py", line 111, in render_compressed
daphne_1  |     cache_key, cache_content = self.render_cached(compressor, kind, mode)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/compressor/templatetags/compress.py", line 89, in render_cached
daphne_1  |     cache_key = get_templatetag_cachekey(compressor, mode, kind)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/compressor/cache.py", line 104, in get_templatetag_cachekey
daphne_1  |     "templatetag.%s.%s.%s" % (compressor.cachekey, mode, kind))
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
daphne_1  |     res = instance.__dict__[self.name] = self.func(instance)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/compressor/base.py", line 200, in cachekey
daphne_1  |     [self.content] + self.mtimes).encode(self.charset), 12)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
daphne_1  |     res = instance.__dict__[self.name] = self.func(instance)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/compressor/base.py", line 194, in mtimes
daphne_1  |     for kind, value, basename, elem in self.split_contents()
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/compressor/js.py", line 17, in split_contents
daphne_1  |     filename = self.get_filename(basename)
daphne_1  |   File "/usr/local/lib/python3.8/site-packages/compressor/base.py", line 159, in get_filename
daphne_1  |     raise UncompressableFileError(
daphne_1  | compressor.exceptions.UncompressableFileError: 'libs/jquery/dist/jquery.min.js' could not be found in the COMPRESS_ROOT '/opt/raveberry/static' or with staticfiles.
```
If I remove my changes and run again, I have the same outcome. 
If I remove the new image and run "$ docker-compose up" without "$ docker build -f docker/Dockerfile -t raveberry/raveberry ." before, I get a functional container again, but without my changes of course.

So I tried removing all the images, making the trivial change again and running "$ docker-compose up" ("without $ docker build -f docker/Dockerfile -t raveberry/raveberry .") but that uses the (working) original image without my code change.

In the [docker documentation](https://docs.docker.com/compose/gettingstarted/#step-5-edit-the-compose-file-to-add-a-bind-mount) I found that "code reloading" seems to be supported. So I added a volume to the docker-compose.yml:

```
daphne:
    image: raveberry/raveberry
    volumes:
      - .:/opt/raveberry
```
but after changing conent (I just added a random line to templates/base.html), stopping removing and starting the containers with "docker-compose up", there were no changes in the file within the container. I wonder if I messed up the path of the volume or if there is anything else I am missing to get code changes into the container.

I will keep trying later :)

**Comment by raveberry** [comment]
Sorry, I forgot to tell you about some other commands that need to be run before building the docker container. The docker setup is only intended to be used in production, that's why setting it up is not as straightforward.
The static files (js, css, images etc.) are served by nginx. Thus, they are contained in the nginx container. Due to the way `django-compressor` works, they need to be in the raveberry container as well. So before building your container, you need to run (which can be found in the depths of the .travis.yml as well):
```
yarn install  # install frontend libraries
scripts/clean_libs.sh  # remove unneeded files created during install
DJANGO_MOCK=1 python manage.py compilescss  # create css files
DJANGO_MOCK=1 python manage.py compress --force  # create js files
```
Note that you need to run the respective command again if you change a css or js file, as well as rebuilding the nginx container.

The code reloading feature could be used for raveberry as well, although not out of the box. Most importantly, the server is not running in development mode, so it won't reload changed files on its own. The development mode also changes the way static files are handled and I'm not sure if it would work in the current setup.
The mounted volume should still help you, though. If you only work with python files, it should be enough to restart the container instead of rebuilding it.

I would recommend you to first build a changed container and only then try to enable the hot code reloading (another feature that already works with `raveberry run` by the way ;) ).

**Comment by copykatze** [comment]
No worries and thanks again! I tried the suggested commands yesterday, but there were more barriers caused by macOS. Installing yarn was required and helped running the first one, but I could not make the second work.
Since I don't want to waste more of your time on this, I figured I try seeting up a dev environment on my raspberry pi 4. So I hooked up a monitor, keyboard and mouse and I got the dev environment running without problems following the contributions-manual. Now I am able to make changes and test them on the dev server right away :-)
My current challenge now is how to test changes that require a system install... Of course I can do a system install on the local machine, but it pulls the code from the original repo and not my fork/branch.

**Comment by raveberry** [comment]
Yes, developing on the pi is probably the best solution. Great that you found a way.

You can do the system install from your dev environment as well. From the folder, run `bin/raveberry system-install` and it will install the contents of the folder. Note that your previous installation will be overriden.

May I ask what you want to do?

**Comment by copykatze** [comment]
Nice, that works! Now I have the original system install (autostarting and served at http://raveberry) and when I run the development server from my forked repo, my fork is served at http://0.0.0.0:8080/ with system integration.
My first goal is just to add a shutdown button to the settings page, because I would like to be able to shutdown gracefully from a chromium kiosk tab as part of my "touchscreen kiosk client" for which I also requested the network info page (#63) which would probably take me forever to implement. Maybe I will try to integrate a telegram bot, but that might be totally out of my reach.
