### ISSUE TITLE
raveberry doesn't like / won't scan the /media folder

### ISSUE THREAD

**Issue by tiny-e** [raveberry/raveberry#75]
My external HD mounts at /media/pi/raveberryhd, with the music being stored in /media/pi/raveberryhd/Music.  Raveberry won't scan this directory.  It says it's going to, but I never see any activity / no music is added.

**Comment by champagj** [comment]
Same issue here on a default manual install on Pi4. Selecting / still does not find files and selecting/media shows the "not valid directory " in the dropdown.
First attempt to install raveberry on 3B+ had some issues but local scanning of the same usb worked fine.
The 3B+ ran regular Buster 
The 4 runs Buster-lite
Could the usb not mount properly on lite version?

**Comment by raveberry** [comment]
Raveberry needs to create a symlink into the specified folder. Some file systems have problems with this (e.g. FAT). Thus, I recommend EXT4, or NTFS for windows interoperability.
You can test if symlinking works: `ln -s /media/pi/ ~/symlink`

Permissions need to be set so the `www-data` can access all files. Does it have read permissions on the files and the containing folders?

Are any errors logged into `/opt/raveberry/logs` when you try to scan the folder?

**Comment by champagj** [comment]
Thanks for the feedack and sugestions. The usb drive was formatted on Win10 anb  I suspect NTFS but could be FAT as well.
I will test and let you know.

**Comment by champagj** [comment]
No errors in the log when scanning. The USB drive was formatted as FAT32. Tested with NTSF, same result, nothing in etiher /media or /mnt and scanning return 0. 
I created a mount point /media/usb and did a manual mount of the usb using sudo mount /dev/sda1 /media/usb -o uid=pi,gid=pi 
Scanning now works and I can play local files.
Is raveberry supposed to scan for newly connected usb and mount them automatically ?

**Comment by raveberry** [comment]
No, it does not add new devices automatically. The device needs to be mounted and visible in the file system. Awesome that you could make it work.

You can define the label of an external medium during installation. Raveberry will add an entry to `/etc/fstab`, mounting it automatically on boot. This is used to move the cache directory away from the Pi's small sd card. You can add a similar entry for your device:
`UUID=<uuid> /mnt/<label> ntfs auto,nofail,noatime,rw,dmask=002,fmask=0113,gid=<www-data gid>,uid=<www-data uid>`
Find the uuid of your device with `blkid`, and the guid and uid of www-data with `id -g www-data` and `id -u www-data`. You might need to change `ntfs` to the file system used on your device.

**Comment by tiny-e** [comment]
my drive(s) are NTFS too, currently mounted to /mnt
`UUID=blahblahblah    /mnt/USBMusic    ntfs    rw,nodev,nosuid,uid=1000,gid=1000,uhelper=udisks2`

/media wouldn't work for me, have not tried manually mounting it there.  

I'm also experiencing the hang / not able to skip behavior with some songs again... no rhyme or reason that I can see.

**Comment by raveberry** [comment]
Since scanning seems to work with a mounted NTFS drive, I'm going to close this issue.
