### ISSUE TITLE
How to make a new (empty) local library?

### ISSUE THREAD

**Issue by vandegraaf** [raveberry/raveberry#76]
I changed the local library path, but it keeps the previous (>20K files).

**Comment by raveberry** [comment]
Yes, changing the library path currently does not delete previous entries. They might contain information that I did not want to be deleted automatically. You need to delete these entries manually with a query (I can provide you with a script if you like).

Songs that can not be found on disk should not appear in suggestions, though. Do the outdated entries impact the performance?

**Comment by vandegraaf** [comment]
I wanted to use raveberry because of the option to rate mp3 files. I'm using different types of mp3 files (music, books, etc.) but after reading 25K of mp3 files it's difficult to find specific files. Since I couldn't find a solution, sorry to say, I went back to only mopidy.
I looked into the database but without documentation I had no way to find out what to do.

Nevertheless thanks for your answer

**Comment by raveberry** [comment]
Large libraries are not easy to deal with and as they are not a core feature, I did not spend that much time implementing them. In the long run I could handle local files with mopidy's database, but that would require some serious refactoring.

I can understand that Raveberry does not suit your needs in this case. Thanks for trying out this project, though!
