### ISSUE TITLE
Playlist Songs getting skipped and no Sound Output to the http://raveberry/stream with Local Files

### ISSUE THREAD

**Issue by PodeCaradox** [raveberry/raveberry#79]
Hello,

i have the problems described above with the Raspberry Pi Zero WH.

First Problem:
![Preview3](https://user-images.githubusercontent.com/5760157/89320317-a07ea100-d681-11ea-83f2-7fb3d412357e.gif).

Also if i load my local Playlist i get no output to the Stream, only with Searched YouTube Songs
My Songs are here: /home/pi/Music/raveberry
with different Folders underneath for the playlists

Edit also Youtube Songs get skipped now.

**Comment by raveberry** [comment]
This is one of the most annoying bugs if it happens. It most likely results from mopidy not being able to play the file, skipping it.
Please post the output of `journalctl -xeu mopidy`, it should contain the corresponding error message.

**Comment by PodeCaradox** [comment]
This is the output from journalctl -xeu mopidy
and yeah i reboot the system between, maybe that's why no error message.
Also still no sound from the http://raveberry/stream and i have no clue why. :/

```

-- Logs begin at Tue 2020-08-04 17:46:32 BST, end at Tue 2020-08-04 21:45:02 BST. --
Aug 04 17:46:57 raveberry systemd[1]: Starting Mopidy music server...
-- Subject: A start job for unit mopidy.service has begun execution
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit mopidy.service has begun execution.
--
-- The job identifier is 101.
Aug 04 17:46:57 raveberry systemd[1]: Started Mopidy music server.
-- Subject: A start job for unit mopidy.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit mopidy.service has finished successfully.
--
-- The job identifier is 101.
Aug 04 17:48:30 raveberry mopidy[359]: INFO     [MainThread] mopidy.__main__ Starting Mopidy 3.0.2
Aug 04 17:48:30 raveberry mopidy[359]: INFO     [MainThread] mopidy.config Loading config from builtin defaults
Aug 04 17:48:30 raveberry mopidy[359]: INFO     [MainThread] mopidy.config Loading config from file:///usr/share/mopidy/conf.d/mopidy.conf
Aug 04 17:48:30 raveberry mopidy[359]: INFO     [MainThread] mopidy.config Loading config from file:///etc/mopidy/mopidy.conf
Aug 04 17:48:30 raveberry mopidy[359]: INFO     [MainThread] mopidy.config Loading config from command line options
Aug 04 17:48:34 raveberry mopidy[359]: INFO     [MainThread] mopidy.__main__ Enabled extensions: http, m3u, softwaremixer, file, stream
Aug 04 17:48:34 raveberry mopidy[359]: INFO     [MainThread] mopidy.__main__ Disabled extensions: spotify, soundcloud
Aug 04 17:48:34 raveberry mopidy[359]: WARNING  [MainThread] mopidy.__main__ Found soundcloud configuration errors. The extension has been automatically disabled:
Aug 04 17:48:34 raveberry mopidy[359]: WARNING  [MainThread] mopidy.__main__   soundcloud/auth_token must be set.
Aug 04 17:48:34 raveberry mopidy[359]: WARNING  [MainThread] mopidy.__main__ Found spotify configuration errors. The extension has been automatically disabled:
Aug 04 17:48:34 raveberry mopidy[359]: WARNING  [MainThread] mopidy.__main__   spotify/username must be set.
Aug 04 17:48:34 raveberry mopidy[359]: WARNING  [MainThread] mopidy.__main__   spotify/password must be set.
Aug 04 17:48:34 raveberry mopidy[359]: WARNING  [MainThread] mopidy.__main__   spotify/client_id must be set.
Aug 04 17:48:34 raveberry mopidy[359]: WARNING  [MainThread] mopidy.__main__   spotify/client_secret must be set.
Aug 04 17:48:34 raveberry mopidy[359]: WARNING  [MainThread] mopidy.__main__ Please fix the extension configuration errors or disable the extensions to silence these messages.
Aug 04 17:48:36 raveberry mopidy[359]: INFO     [MainThread] mopidy.commands Starting Mopidy mixer: SoftwareMixer
Aug 04 17:48:36 raveberry mopidy[359]: INFO     [MainThread] mopidy.commands Starting Mopidy audio
Aug 04 17:48:36 raveberry mopidy[359]: INFO     [MainThread] mopidy.commands Starting Mopidy backends: FileBackend, M3UBackend, StreamBackend
Aug 04 17:48:36 raveberry mopidy[359]: INFO     [Audio-2] mopidy.audio.actor Audio output set to "rgvolume ! audioconvert ! audioresample ! pulsesink server=127.0.0.1"
Aug 04 17:48:37 raveberry mopidy[359]: INFO     [MainThread] mopidy.commands Starting Mopidy core
Aug 04 17:48:37 raveberry mopidy[359]: INFO     [MainThread] mopidy.commands Starting Mopidy frontends: HttpFrontend
Aug 04 17:48:37 raveberry mopidy[359]: INFO     [HttpFrontend-8] mopidy.http.actor HTTP server running at [::ffff:127.0.0.1]:6680
Aug 04 17:48:37 raveberry mopidy[359]: INFO     [MainThread] mopidy.commands Starting GLib mainloop

```

**Comment by raveberry** [comment]
It says `Audio output set to "rgvolume ! audioconvert ! audioresample ! pulsesink server=127.0.0.1"`. Did you press the "Enable streaming" button in `/settings`?
This should change the `output` key in `/etc/mopidy/mopidy.conf` to `output = rgvolume ! audioconvert ! audioresample ! lamemp3enc ! shout2send async=false mount=stream`, moving the output from the local device to the iceacast stream.

**Comment by PodeCaradox** [comment]
> 
> 
> It says `Audio output set to "rgvolume ! audioconvert ! audioresample ! pulsesink server=127.0.0.1"`. Did you press the "Enable streaming" button in `/settings`?
> This should change the `output` key in `/etc/mopidy/mopidy.conf` to `output = rgvolume ! audioconvert ! audioresample ! lamemp3enc ! shout2send async=false mount=stream`, moving the output from the local device to the iceacast stream.

Yes i enabled streaming, because i need to have stream on 2 other devices, is this wrong?

**Comment by PodeCaradox** [comment]
Ok after reboot it work now with the Playlist.
One thing i noticed is if i skip a song the stream is long in silence and i need to reload the stream page.
Also if the next Song is coming up it is 3-4 Seconds silence after the next Song will be played. Do you have maybe a fix for that or is it because of the raspberry pi slowing it down?

**Comment by raveberry** [comment]
I asked because Raveberry should handle the config change on its own. Apparently there is still some bug if it didn't update.
The stream disconnects are best discussed in [this issue](https://github.com/raveberry/raveberry/issues/47) you already found.

Great that streaming works at all now, though.
