### ISSUE TITLE
Spotify search for Artist and Album

### ISSUE THREAD

**Issue by 8sd** [raveberry/raveberry#8]
`search_id` and `id_from_external_url` have to be changed

**Comment by raveberry** [comment]
With 0.8.2, playlist queries in Spotify first try to find an artists top-tracks, then an album and lastly a playlist. This allows for more flexibility while keeping the interface concise.
Hopefully this does not lead to unexpected results when people tried to queue a playlist but got an album. In that case we'd have to readjust.
