### ISSUE TITLE
More shuffle functionality

### ISSUE THREAD

**Issue by tiny-e** [raveberry/raveberry#80]
I'm not sure how the playlist feature works... looks like it scans the library for folders and creates a playlist for each folder(?).

My music is organized as:  Artist Name/Album/Song.mp3, so there's a zillion folders.. 

Is there way to give it a playlist to start on, to prime the pump, as it were?   Maybe one it can shuffle?

**Comment by raveberry** [comment]
> looks like it scans the library for folders and creates a playlist for each folder(?).

Yes, exactly. If you click the "Create Playlists" button, Raveberry will create one playlist for every folder. These playlists will contain every song they directly contain. So you will have one playlist per album. None for artists will be created, because I did not want to assume folder structure.

You can then enqueue playlists by pressing the button to the left of the dice, enabling "playlist mode". Now, every query will result in a playlist, enqueuing multiple songs. Search for the name of the Album and it should show up in the suggestions.

Currently, there is now way to shuffle the queue. You can enable shuffle if voting is disabled, so a random song will be played instead of the first one. Alternatively, you can drag them around manually.

**Comment by tiny-e** [comment]
So, I think it would be easy enough for me to make a list of everything in there as a m3u list.. but it would be cool if there was an initial shuffle to populate the queue, and then allow voting happen from there.

**Comment by tiny-e** [comment]
Or to have a 'shuffle all' feature, but allow for voting --putting requested items ahead of the shuffled content.. 

(sorry I'm so full of good ideas :D )

**Comment by raveberry** [comment]
What do you plan to do with the m3u file?

A "shuffle queue" button is a reasonable addition I will consider. It would randomly reorder the queue and work in both voting and normal mode. This way voted songs will still go above the other songs, but all songs with the same vote count are randomly ordered.

Keep your ideas coming! Feedback allows me to understand how other people use this software and I can use it to make Raveberry even better. Please just don't be mad if I don't implement them all right away (or at all), as unfortunately I have other things to do as well. ;)

**Comment by tiny-e** [comment]
No worries -- Here's my goal:
Arrive 
Press "play" -- some random songs, or a list that I've curated starts playing (also preferably shuffled).
People can access with webUI and search/vote
Drink beer and not have to manage it too much / bring a laptop with me..

**Comment by raveberry** [comment]
So you'd need a way to create playlists other than those containing of contents of a single folder, if I understand that correctly. It would definitely be a nice feature to have and eventually I want to include it. However, it's not quite easy to implement and it requires some non-trivial UI. So unfortunately it will not be part of Raveberry in the near future.

Still, there is a (only kinda hacky) workaround that is already possible:
Create a Folder in the specified local library with the name of your desired playlist. Fill the folder with hardlinks to the songs that should be in this folder. Symlinks won't work as Raveberry actually checks if the contents are files. This way you do not need to create copies of your songs. I understand that this is not ideal, but if you really want to do this it should be possible.

As for the shuffle feature: That is not too hard to add. I will probably include it soonish.

**Comment by tiny-e** [comment]
Thanks -- Are you aware of any playlist builder that would handle hardlinking all those files?   Disk space being what it is, it may be easier to make a folder like "Mix" or something in there that contains the files. 

A shuffle-all feature that basically cues up X songs would be pretty cool.

**Comment by raveberry** [comment]
No, I don't know of a tool that could do this.
If disk space is not a concern and you don't mind having duplicate files you can simply just copy them into this new folder, that's right.

The shuffle-all feature could be interesting. Even so, I'm a little skeptic about queuing random songs from Raveberry's database. Over time a lot of songs are amassed in its database, some of which might have been added accidentally. Additionally, a random selection of these songs probably won't fit together at all. However, the random suggestions feature already exists, so implementing the "add x random songs" should not be too complicated, I might just add it.

**Comment by tiny-e** [comment]
Thanks -- I think it would be perfect for certain scenarios (like mine).  The collection of local files is somewhat curated by me beforehand (or will be), which should be enough to let things develop organically from there, playlist-wise.

**Comment by raveberry** [comment]
With 0.8.5 it is now possible to shuffle the whole queue (new button next to the big trashcan). If voting is enabled, only the ordering between songs with the same vote count will change, otherwise the whole queue is shuffled. It's fun to see all the songs move around to their new position.
