### ISSUE TITLE
Can I change the admin user name? 

### ISSUE THREAD

**Issue by tiny-e** [raveberry/raveberry#82]
I can see the area where I can edit the users in the database and tried making another admin account, but it gets kicked to the "generic" user page when I try to login. 

If I change the name of the admin user in the Django admin settings, will that break anything?

**Comment by raveberry** [comment]
Currently Raveberry is [hardcoded](https://github.com/raveberry/raveberry/blob/9f9186fa74a8c6393f66f3c23f2e227bf0881c37/core/user_manager.py#L26) to check for the "admin" username. However, it's trivial to change this to `user.is_superuser` which would work with other usernames as well.

I will include this change in the next update, as it does not break anything else.

May I ask why you need another admin account? Couldn't you just give the credentials to all admin users?

**Comment by tiny-e** [comment]
If I expose this to the internet, I'd feel better about knowing that the default admin account could be anything besides "admin" to make brute-forcing more difficult.   (let me know if you think I'm being over cautious here.. )

**Comment by raveberry** [comment]
No, this is definitely a reasonable concern. Will be included in the next update.

**Comment by raveberry** [comment]
In 0.7.2 the check was changed to check for the user's status instead of its username. You should now be able to use different usernames for the admin user.
