### ISSUE TITLE
QR codes-  Generated Network QR code isn't for the hotspot SSID/Password

### ISSUE THREAD

**Issue by tiny-e** [raveberry/raveberry#87]
Tried this out over the weekend.  The top QR Code tries (and failed) to provide login details about my home WIFI network, and not the Pi's hotspot (called 'Raveberry') --which also borks the Raveberry URL QR code as my home network won't resolve that subnet (192.168.4.1).

**Comment by raveberry** [comment]
This feature was implemented for use cases where you don't which IP the Raveberry has and the router does not perform DNS resolution. It was cumbersome to find out how to even access it. Someone with a display connected to the Pi [suggested](https://github.com/raveberry/raveberry/issues/63) this page so they would always be able to know the Pi's IP.

The current Implementation breaks when the hotspot is active, as I did not program it for that use case. With a hotspot, you always know it's IP and the wifi password, after all. Would you actually use this feature with an active hotspot?

**Comment by tiny-e** [comment]
I could see a use case for me as I could show a potential user the QR
code on my phone, and they'd be all set.  I suppose I could use 3rd
party tools/sites to do this as long as I keep the SSID / Password the
same.

**Comment by tiny-e** [comment]
I could see a use case for me as I could show a potential user the QR code
on my phone, and they'd be all set.  I suppose I could use 3rd party
tools/sites to do this as long as I keep the SSID / Password the same.

**Comment by raveberry** [comment]
I changed the feature to correctly handle both interfaces. It will be available in the next update.

**Comment by raveberry** [comment]
0.7.5 was just released with this feature
