### ISSUE TITLE
Streaming -- Not working, getting sent to "Silence" Mountpoint.  Stream mountpoint not showing up in admin interface

### ISSUE THREAD

**Issue by tiny-e** [raveberry/raveberry#89]
![image](https://user-images.githubusercontent.com/2148511/92040909-d4aab780-ed3c-11ea-8243-f32448a67ecf.png)

Just did a fresh reinstall of OS and Raveberry, enabled streaming (which worked before) and I'll I ever get is the silence mount in icecast2.  I can see that raveberry made it's mount in the icecast config, but it doesn't show up..

**Comment by raveberry** [comment]
Is the mopidy config correct? It should contain `output = [...] ! shout2send async=false mount=stream`
Do any of the services `mopidy` or `icecast2` show any errors in their logs, same for `/opt/raveberry/logs`.

Also, a song needs to be playing in order for the stream mountpoint to appear.

**Comment by tiny-e** [comment]
I will try to check this out in the next few days and report back. --Thanks

**Comment by raveberry** [comment]
I encountered this issue today as well. An update of the libshout library apparently broke the streaming functionality in mopidy. Until a fix is released in the repos, you can downgrade the library to make it work again:
```
cd /tmp
wget http://mirrors.kernel.org/ubuntu/pool/main/libs/libshout/libshout3_2.4.1-2build1_amd64.deb
sudo dpkg -i libshout3_2.4.1-2build1_amd64.deb
sudo apt-mark hold libshout3
```
More info: https://jc-lan.org/2020/05/26/mopidy-fails-to-connect-to-icecast2-server-with-ubuntu-20-04/

**Comment by raveberry** [comment]
Added a section into the FAQ.
