### ISSUE TITLE
Volume normalization

### ISSUE THREAD

**Issue by 8sd** [raveberry/raveberry#9]
`aacgain` takes ages to build…
Since we are using `gstreamer` now there might be an easier possibility, maybe even without using `replaygain`?

**Comment by raveberry** [comment]
Added in cd3f4c14821870c4a7e0aac0e5adc938a014b2ae.
There is the [rgvolume](https://gstreamer.freedesktop.org/documentation/replaygain/rgvolume.html) element in gstreamer which levels the input according to tagged replaygain.
I also found [another tool](https://github.com/DarwinAwardWinner/rganalysis/) that can tag aac files. We still have to build some libraries ourselves, but at least the setup is a little more straight-forward than before.
