### ISSUE TITLE
Hashtags

### ISSUE THREAD

**Issue by clovnix** [raveberry/raveberry#90]
Simple question I hope.

How to edit or delete the Hashtags, that users can insert in the top of the UI. 
I just found some binary files with grep, but i dont know how to edit these things.

Hope someone can help. 
Thanks for the great software :)

**Comment by joroec** [comment]
Hi,
the hashtags are stored in a relational data base alongside the other data (e.g. current playlist). You can find the hashtags in the relation "Tag".  Depending on your setup, you access the data base in different ways. Most probably, your installation relies on the postgres data base that is set up in the docker-compose.yml file.

If so, you can use `docker container ls -a` to find the postgres container of your deployment. The correct one is the one that uses 'postgres' as an image. Copy the container ID. Then, you can execute a shell in the container with the command `docker exec -it <id> /bin/bash`. You have now a shell in the container.

Finally, you can connect to the database, just type `psql -U raveberry -d raveberry`. You are now in a SQL shell and have access to the data base. You have access to all the hash tags.

For example, you can list all hash tags with:
```
SELECT * FROM Tag;
```
For more information on how to modify / access the data, refer to a [SQL tutorial](https://www.w3schools.com/sql/).

As I am not using raveberry at the moment, those commands are not fully tested. Just try it and report back if something is not working properly.

Hope that helps.

**Comment by raveberry** [comment]
Thanks for the detailed answer, @joroec. If you want to directly connect to the database, this is the way to go.

However, if you simply want to edit/delete some hashtag entries, you can go to django's admin interface. Visit `raveberry/admin` and log in with your admin password. You will see all tables used by Raveberry, click on "Tags". There you can modify and delete the entries from your browser.
