### ISSUE TITLE
cannot install 

### ISSUE THREAD

**Issue by Crushedice** [raveberry/raveberry#92]
raveberry system-install 

E: Unable to locate package libspotify-dev

E: Unable to locate package mopidy-spotify
Could not install required dependencies

**Comment by raveberry** [comment]
This looks like mopidy's archive was not installed correctly.
What happens if you try to add it manually:
```
wget -q -O - https://apt.mopidy.com/mopidy.gpg | apt-key add -
wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/buster.list
apt update
```
Also: which system are you trying to install Raveberry on?

**Comment by Crushedice** [comment]
solved myself.
 i dont know what went wrong there, i tried many things. somewhat wasted my time.
WAS running Ubuntu 20.04LTS server on PI 4 
I then just formated everything, put Raspberry OS lite from the raspberry imager tool on it.
-Updated the base system
- Installed Docker  + Docker-Compose for it ( didnt know before thats 2 seperate things.) - [https://devdojo.com/bobbyiliev/how-to-install-docker-and-docker-compose-on-raspberry-pi](url)
from then, i followed your guide here on github,
and that worked out fine. 
Thank you ! 

While i'm on it -  quick question,  is there a way to bind the server to a hostname , undependend from the network?
Im struggeling currently inside a domainnetwork to access the server.

**Comment by raveberry** [comment]
Great that you could make it work!

What do you mean by binding the server to a hostname? You can set the hostname of your Raspberry pi with the `hostname` command and persist it by modifying `/etc/hostname`. Some routers will then automatically route traffic to the Pi.

There is also the possibility to have the Pi connect to a server that will forward all traffic. However, this feature is only available in a system install, not with docker.
