### ISSUE TITLE
[Request] Radio Stream 

### ISSUE THREAD

**Issue by Crushedice** [raveberry/raveberry#93]
Greetings,
first of all, i wanted to say :   Awesome app,  exactly what i  was searching for , for my workplace ( we are currently ~6 people working together and always arguing about the music.)  .

Now then, i wanted to request if we could add some internet Radio stream to play ,  for cases if nobody queued any songs, so the music  doesnt just turn off. 
Also , is there a way to display all songs that are avalible / Have previously been playing to pick from? 

And, what is the function of the Tags on top?

**Comment by raveberry** [comment]
Glad to hear that you like it!

Mopidy [already supports internet streams](https://docs.mopidy.com/en/latest/ext/stream/), so it should not be too complicated to add that functionality. 
The question is how it should be accessible interface-wise. I could make it possible to add radio streams just like normal songs. Then they could be voted for and as soon as a stream reaches the top of the queue, the stream is played. However, the stream would continue playing indefinitely until a moderator skips the stream.
Alternatively I could add the possibility to specify a fallback stream either in the settings or the main page. Then Raveberry would play the stream as soon as no more songs are available and stop when the next song is added.
I think I'm in favor of the second solution, what do you think?

Raveberry's interface does not provide a possibility to look through all previously played songs. However, you can use django's admin interface at `http://raveberry/admin` (login with your admin credentials) and navigate to "Archived Songs". This is the database containing all songs that have been played.

The Tags thing on top allows everyone to add words or short phrases as tags. Each page reload displays one of these collected tags. It can be used for running gags, puns or something similar to put a smile on the users of the page :)

**Comment by scls19fr** [comment]
https://www.radio-browser.info/ provides a large number of webradio streams and have a free API.
See https://github.com/segler-alex/radiobrowser website frontend for radio-browser api (with angular)
there's also an Android app called RadioDroid https://github.com/segler-alex/RadioDroid which can interact with Music Player Daemon.

**Comment by Crushedice** [comment]
Ya. The second method sounds pretty good. 
Specially cause, there are times when nobody adds music, and nothing was automaticly added to the list, then it falls silent.

Got some complains about " no music" and " i dont want to add always anything to the list" .
So the fallback stream would be pretty nice honestly.

**Comment by scls19fr** [comment]
https://api.radio-browser.info/ could help
And if you are looking for a Python client to interact with this server. You can have a look at https://github.com/andreztz/pyradios/
I suggest using the recently added cache requests (see https://github.com/andreztz/pyradios/pull/7)
I should avoid too much requests to their servers

**Comment by Crushedice** [comment]
i ment a api for raveberry, to interact with .

**Comment by Crushedice** [comment]
Also Just another small addition that i would like.  
To make the Dice button for "Random songs" avalible to everyone , maybe as setting.
Im slowly filling up the drive with my own collections, so just clicking a few times on random is for some better then searching for a name or getting a link.

**Comment by raveberry** [comment]
> Do you have any API avalible to communicate with the server ?

There is no clearly specified API. However, you can take a look at [this file](https://github.com/raveberry/raveberry/blob/master/core/urls.py). It defines all url enpoints and should provide some insights. What do you have in mind?



> make the Dice button for "Random songs" avalible to everyone , maybe as setting.

What do you mean? The dice button should already be available to everyone, even in voting mode.

Also, please consider opening a new issue for new questions. It helps separating discussions :)

**Comment by Crushedice** [comment]
ah right. just saw the button. didnt noticed it before. sry. 

What i got in mind, well just thought about taking a look at it and see if i can build 
a small desktop client ( As i mainly work with Cs ) .
Will let you know if i get to any result.

**Comment by raveberry** [comment]
With v0.7.8 a backup stream can now be provided in the settings!
It is started after the last song in the queue and automatically stops if another song is queued.
Let me know if this works for you.

**Comment by deep5050** [comment]
radioactive is a CLI-based intrnet radio player with 40K+ stations with recording support
you can try it

pip install git+https://github.com/deep5050/radio-active@2.7.0
