### ISSUE TITLE
Unable to save spotify credentials

### ISSUE THREAD

**Issue by 0anth** [raveberry/raveberry#97]
I enter my logon credentials, client ID and secret, then press "set credentials" and an info box appears with a green tick saying "Updated credentials". 

If I reload the page, the credentials are all blank again.

**Comment by akyjoe** [comment]
> I enter my logon credentials, client ID and secret, then press "set credentials" and an info box appears with a green tick saying "Updated credentials".
> 
> If I reload the page, the credentials are all blank again.

Try checking the credentials in the dJango backend: <IP-Address>/admin/core/setting/

**Comment by 0anth** [comment]
I can't find this folder. Where is it located exactly? I'm running rasbian.

**Comment by raveberry** [comment]
The input fields on the settings page are not supposed to show the credentials. If you want to check whether they are correct you can look in two locations:
1. `/etc/mopidy/mopidy.conf`: this is where mopidy needs them so the are put into this file
2. visit `http://raveberry/admin/core/setting/`, which shows the database table containing all raveberry-related settings. This is what @akyjoe meant.

**Comment by 0anth** [comment]
Ok, so I checked mopidy.conf and my details were in there. I checked /admin/core/settings/ and my details were also in there, though "spotify_enabled" was set to false. I set this to true. It now looks like:

![/admin/core/settings/](https://i.imgur.com/6bXB0jk.png)

However, the settings page still shows blank, but with spotify now enabled:

![settings page](https://i.imgur.com/j1HTcA0.png)

When searching songs, spotify now returns results. However when I select a song, it attempts to play it, then immediately says the song is finished, but nothing actually plays.

**Comment by raveberry** [comment]
The settings page will not show your Spotify credentials, it is input-only. If the credentials show up in the database/the config file, they were processed correctly.

Please do not change settings directly from the django backend, as Raveberry might do things other than updating the database. For enabling Spotify, you should do so through the settings page and tick the "Spotify enabled" checkbox. Maybe disabling and reenabling it works.

Providing suggestions works a little differently than playing songs. Since the suggestions work, I suspect a problem with the player. Is there any useful information in mopidy's log, possibly about a failed login or something?
You can view it with `journalctl -xeu mopidy`.

**Comment by 0anth** [comment]
I tried to play a song, then checked the log. I found this single line:
`[SpotifyBackend-6] mopidy_spotify.lookup Failed to lookup 'spotify:track:5xYC48nOppVemY6U5GRGTb': Session must be logged in and online to load objects: <ConnectionState.LOGGED_OUT: 0>`

I then unchecked the "enabled" box under the Spotify section, when I tried to check it again to enable it, I got this error (dispite the details being in the database still):

![Screenshot_20210108-165637_Chrome](https://user-images.githubusercontent.com/1083462/103995485-823e4380-51d3-11eb-8b81-1c3552177cc4.jpg)

**Comment by 0anth** [comment]
As an update, I found these two lines in the log:
`mopidy[549]: ERROR    [SpotifyEventLoop] spotify.session Spotify login error: <ErrorType.USER_NEEDS_PREMIUM: 15>`
`mopidy[549]: WARNING  [SoundCloudBackend-7] mopidy_soundcloud.soundcloud SoundCloud daily rate limit exceeded (Too Many Requests)`

It does not say anywhere in raveberry or the raveberry github that Spotify premium is required. Is Spotify premium required?
I also assume the soundcloud issue is being caused by having a "free" soundcloud account.

**Comment by zigapovhe** [comment]
> As an update, I found these two lines in the log:
> `mopidy[549]: ERROR [SpotifyEventLoop] spotify.session Spotify login error: <ErrorType.USER_NEEDS_PREMIUM: 15>`
> `mopidy[549]: WARNING [SoundCloudBackend-7] mopidy_soundcloud.soundcloud SoundCloud daily rate limit exceeded (Too Many Requests)`
> 
> It does not say anywhere in raveberry or the raveberry github that Spotify premium is required. Is Spotify premium required?
> I also assume the soundcloud issue is being caused by having a "free" soundcloud account.

Yes, Spotify integrated media controls (pause, play, next, etc.) require a Premium account.

**Comment by raveberry** [comment]
Yes, Spotify Premium is needed in order to use the mopidy extension that is used for Spotify playback.
I'm sorry that I didn't mention it anywhere. I will put it in the readme and show a more meaningful error message.

**Comment by raveberry** [comment]
Done in v0.7.8
